### PR TITLE
roadId ist nicht auf Autobahnen beschränkt

### PR DESCRIPTION
**Pull request by mvglasow**
Siehe #19.

### CODE REVIEW

**Comment by t-huyeng** [comment]
LGTM, 
can you maybe add an Example for other RoadId than a Autobahn?

Maybe like this:
```
    examples:       # Multiple examples
      autobahn:         
        value: A1    
        summary: Autobahnnummer
      bundesstrasse: 
        value: ?
        summary: Bundesstrasse
  ```

If `bundesstrasse` is working.

Thanks!

**Comment by mvglasow** [comment]
Done, hope I did it correctly

**Comment by mvglasow** [comment]
I also added a sentence for non-standard roadId formats (e.g. S rather than St for Staatsstraßen).

**Comment by t-huyeng** [comment]
Sorry, my advice was wrong. I looked at the documentation again:
`Note that multiple example values per property or schema are not supported ...`.

And so the OpenAPI Check also fails:
```
 354:16 error oas3-schema Property "examples" is not expected to be here. components.schemas.RoadId.examples
 ```
 
 Would you be so kind as to change this back to a single simple example. I think the description is enough for now.

**Comment by t-huyeng** [comment]
Thanks @mvglasow !

**Pull request merged**
